### ISSUE TITLE
Checklist Routes

### ISSUE THREAD

**Issue by GAFelton** [GAFelton/zen-app#26]
### Checklist Routes
- [x] "/api/list"  GET
does a findAll statement on the checklist database.

- [x] "api/list/completed"  GET
returns all checklist items where `completed: 1, hidden: 1`

- [x] "api/list/:id"  GET
returns a checklist item matching the particular id.

- [x] "api/list"  POST
add a new checklist entry to the checklist database. Takes in value, user.

- [ ] "api/list/:id"  PUT
makes a particular checklist entry `completed: 1, hidden: 1` for the specified id.

**Comment by GAFelton** [comment]
- [x] "api/list/completed/:id" PUT

makes a particular checklist entry completed: 1 for the specified id.

 - [x] "api/list/hidden/:id" PUT

makes a particular checklist entry hidden: 1 for the specified id.
